"""[A module to test the news_data_handling.py module and its methods]
    """
from news_data_handling import news_API_request, update_news


def test_news_API_request():
    """[A function to test the news_API_request method]
    """
    assert news_API_request()
    assert news_API_request('Covid COVID-19 coronavirus') == news_API_request()


def test_update_news():
    """[A function to test scheduling news updates]
    """
    update_news('test')


def process_news_api(articles_current: dict, headlines) -> dict:
    """[A function to remove unwanted news from the news collected by the API]

    Args:
        articles_current (dict): [the API collected news]

    Returns:
        dict: [the filtered news articles]
    """
    global ARTICLES
    i = 0
    for news in articles_current:
        for j in range(0, len(headlines)):
            if news['title'] == headlines[j]:
                # adding the full data to the config file headlines
                headlines[j] = news
        i += 1
    # removing the unwanted news from the API data
    ARTICLES = [x for x in articles_current if x not in headlines]
    #logger_news_handler.info('Articles have been filtered and processed')
    return ARTICLES  # return the processed API data


def test_process_news_api():
    """[A function to test if news is correctly removed]
    """
    headlines = ['Covid 19 Delta outbreak: People in Nelson urged to get tested as community cases rise - New Zealand Herald',
                 "PH logs 564 new Covid-19 cases, year's lowest positivity rate - The Manila Times",
                 "COVID-19: Omicron has 'substantial' ability to evade immunity from previous coronavirus infection - Sky News",
                 'Germany imposes COVID-19 restrictions on unvaccinated, proposes vaccine mandate - ABC News']
    articles_current = [{'source': {'id': None, 'name': 'The Manila Times'}, 'author': 'Red Mendoza', 'title': "PH logs 564 new Covid-19 cases, year's lowest positivity rate - The Manila Times", 'description': 'THE Philippines reported 564 new cases of the coronavirus disease 2019 (Covid-19) on Thursday, as the test positivity rate dropped to its lowest for the year at 1.7 percent,...', 'url': 'https://www.manilatimes.net/2021/12/03/latest-stories/ph-logs-564-new-covid-19-cases-years-lowest-positivity-rate/1824583', 'urlToImage': 'https://www.manilatimes.net/manilatimes/uploads/images/2021/12/03/31234.jpg', 'publishedAt': '2021-12-02T20:31:03Z', 'content': 'THE Philippines reported 564 new cases of the coronavirus disease 2019 (Covid-19) on Thursday, as the test positivity rate dropped to its lowest for the year at 1.7 percent, according to the Departme… [+602 chars]'},
                        {'source': {'id': 'politico', 'name': 'Politico'}, 'author': 'Ben White', 'title': 'Biden is looking at blowout growth even as Covid clouds the outlook again - Politico', 'description': "Republicans are seeking to capitalize on the anxiety over higher prices, saying that they're largely driven by Biden's big-spending plans.", 'url': 'https://www.politico.com/news/2021/12/02/biden-virus-wall-street-523670',
                            'urlToImage': 'https://static.politico.com/6c/39/1e97893b480cb292f38f037a8529/211202-biden-ap-773.jpg', 'publishedAt': '2021-12-02T20:22:36Z', 'content': 'Morgan Stanley recently cranked up its growth estimate for the last three months of the year to an annualized rate of 8.7 percent from 3 percent because of strong consumer demand and declining jobles… [+5300 chars]'},
                        {'source': {'id': None, 'name': 'Sky.com'}, 'author': 'Thomas Moore', 'title': "COVID-19: Omicron has 'substantial' ability to evade immunity from previous coronavirus infection - Sky News", 'description': '',
                            'url': 'https://news.sky.com/story/covid-19-omicron-has-substantial-ability-to-evade-immunity-from-previous-coronavirus-infection-12484840', 'urlToImage': 'https://e3.365dm.com/21/12/1600x900/skynews-omicron-south-africa_5602568.jpg?20211202201256', 'publishedAt': '2021-12-02T20:15:00Z', 'content': None},
                        {'source': {'id': None, 'name': 'CNBC'}, 'author': 'Spencer Kimball', 'title': "Biden says he doesn't want lockdowns and won't expand vaccine mandates to fight Covid this winter - CNBC", 'description': "President Joe Biden said on Thursday his plan to fight Covid during the winter doesn't include shutdowns or lockdowns.", 'url': 'https://www.cnbc.com/2021/12/02/covid-news-biden-says-no-lockdowns-wont-expand-vaccine-mandates-this-winter.html',
                         'urlToImage': 'https://image.cnbcfm.com/api/v1/image/106983760-16384709102021-12-02t184732z_1671758560_rc2h6r9yz1cs_rtrmadp_0_health-coronavirus-usa-biden.jpeg?v=1638470937', 'publishedAt': '2021-12-02T20:09:23Z', 'content': 'President Joe Biden on Thursday said his plan to fight Covid during the winter months will not include new lockdowns or an expansion of the administration\'s current vaccination requirements.\r\n"It doe… [+3425 chars]'},
                        {'source': {'id': 'cbc-news', 'name': 'CBC News'}, 'author': None, 'title': 'COVID-19 boosters to open to Ontarians 50+ as of Dec. 13, province reports 959 new cases - CBC.ca', 'description': 'Ontario reported 959 new cases of COVID-19 on Thursday, while the province announced the expanded\xa0eligibility for vaccine booster shots to those aged 50 and older.', 'url': 'https://www.cbc.ca/news/canada/toronto/covid-19-ontario-dec-2-2021-vaccine-boosters-50-plus-1.6270871',
                         'urlToImage': 'https://i.cbc.ca/1.5979496.1617892847!/cumulusImage/httpImage/image.jpg_gen/derivatives/16x9_620/places-of-worship-vaccinations.jpg', 'publishedAt': '2021-12-02T19:41:10Z', 'content': 'Ontario reported 959 new cases of COVID-19 on Thursday, while the province announced the expanded\xa0eligibility for vaccine booster shots to those aged 50 and older.\r\nIn a news release issued Thursday … [+6134 chars]'},
                        {'source': {'id': None, 'name': 'Stuff.co.nz'}, 'author': None, 'title': 'Covid-19: Positive community case confirmed in Coromandel - Stuff.co.nz', 'description': 'The person was in Whitianga and tested positive on Thursday afternoon, but it was an isolated case with low risk of spread.', 'url': 'https://www.stuff.co.nz/waikato-times/news/300469309/covid19-positive-community-case-confirmed-in-coromandel',
                         'urlToImage': 'https://resources.stuff.co.nz/content/dam/images/4/y/v/r/5/r/image.related.StuffLandscapeSixteenByNine.1420x800.4yw3lp.png/1638477034879.jpg', 'publishedAt': '2021-12-02T19:29:00Z', 'content': 'A case of Covid-19 has popped up on the Coromandel Peninsula.\r\n A statement from the Thames Coromandel District Council said the case was in Whitianga and was confirmed on Thursday afternoon.\r\n It wa… [+1266 chars]'},
                        {'source': {'id': 'the-irish-times', 'name': 'The Irish Times'}, 'author': 'Simon Carswell', 'title': "Covid numbers 'stabilising' but still present 'huge risk' - Reid - The Irish Times", 'description': 'HSE says falling case numbers among older people due to boosters a ‘cause for hope’', 'url': 'https://www.irishtimes.com/news/health/covid-numbers-stabilising-but-still-present-huge-risk-reid-1.4745280',
                         'urlToImage': 'https://www.irishtimes.com/image-creator/?id=1.4745279&origw=1440', 'publishedAt': '2021-12-02T19:03:56Z', 'content': 'Covid-19 numbers have stabilised but at an extremely high level presenting a huge risk to the health service heading into the winter period, HSE chief executive Paul Reid has said.\r\nHe told the HSEs … [+4486 chars]'},
                        {'source': {'id': 'abc-news-au', 'name': 'ABC News (AU)'}, 'author': 'ABC News', 'title': 'Germany imposes COVID-19 restrictions on unvaccinated, proposes vaccine mandate - ABC News', 'description': 'Germany bans unvaccinated people from non-essential stores and venues, and considers making vaccines\xa0mandatory as new case numbers hit 70,000 in 24 hours.', 'url': 'https://www.abc.net.au/news/2021-12-03/germany-imposes-restrictions-on-the-unvaccinated/100671070',
                         'urlToImage': 'https://live-production.wcms.abc-cdn.net.au/81d694c5317ea01a8c781bdc99a0e32a?impolicy=wcms_crop_resize&cropH=1316&cropW=2340&xPos=0&yPos=99&width=862&height=485', 'publishedAt': '2021-12-02T18:56:22Z', 'content': "German Chancellor Angela Merkel says people who are not vaccinated will be barred from non-essential stores, and cultural and recreational venues.\r\nKey points:\r\n<ul><li>Germany's leaders are consider… [+3969 chars]"},
                        {'source': {'id': None, 'name': 'CKPGToday.ca'}, 'author': None, 'title': 'Combined COVID-19 and Influenza vaccine clinic being offered on Friday - CKPGToday.ca', 'description': 'PRINCE GEORGE- A drop-in COVID-19 and Flu vaccine clinic is being offered by Carrier Sekani Family Services an...', 'url': 'https://ckpgtoday.ca/2021/12/02/combined-covid-19-and-influenza-vaccine-clinic-being-offered-on-friday/',
                         'urlToImage': 'https://s3.amazonaws.com/socast-superdesk/media/20211202181240/2bf4f15a-bfe5-47c8-9a78-4a2c992ecf60.jpg', 'publishedAt': '2021-12-02T18:44:00Z', 'content': 'PRINCE GEORGE- A drop-in COVID-19 and Flu vaccine clinic is being offered by Carrier Sekani Family Services and Northern Health tomorrow (Friday). The clinic is taking place at CSFS’s main office at … [+456 chars]'},
                        {'source': {'id': None, 'name': 'Sky.com'}, 'author': 'Andy Hayes, news reporter', 'title': 'COVID-19: Mandatory jabs considered in Germany from February as tougher restrictions brought in for unvaccinated - Sky News', 'description': '',
                         'url': 'https://news.sky.com/story/covid-19-jabs-to-be-mandatory-in-germany-from-february-as-tougher-restrictions-brought-in-for-unvaccinated-12484587', 'urlToImage': 'https://e3.365dm.com/21/12/1600x900/skynews-coronavirus-germany_5602277.jpg?20211202144943', 'publishedAt': '2021-12-02T18:22:30Z', 'content': None},
                        {'source': {'id': None, 'name': 'New Zealand Herald'}, 'author': None, 'title': 'Covid 19 Delta outbreak: People in Nelson urged to get tested as community cases rise - New Zealand Herald', 'description': 'People in Nelson are being urged to get a Covid test as a number of cases have been found.', 'url': 'https://www.nzherald.co.nz/nz/covid-19-delta-outbreak-people-in-nelson-urged-to-get-tested-as-community-cases-rise/WVGNGRBZRDI2BI55EKQIHF45B4/',
                         'urlToImage': 'https://www.nzherald.co.nz/resizer/whRXZWy0Sgyl6pqigWiHuAvjo_4=/1200x675/filters:quality(70)/cloudfront-ap-southeast-2.images.arcpublishing.com/nzme/W46D7ZPEDPAUFAKEWZZ5C3ATTM.jpg', 'publishedAt': '2021-12-02T18:03:00Z', 'content': 'The country prepares to move into the Covid-19 Protection framework a.k.a traffic light system. Video / NZ Herald\r\nPeople in Nelson are being urged to get a Covid test as the number of community case… [+1203 chars]'},
                        {'source': {'id': None, 'name': 'RNZ'}, 'author': 'RNZ News', 'title': 'Live updates: Traffic light system operational, Aucklanders emerge from lockdown - RNZ', 'description': 'After nearly four months, Aucklanders have emerged from lockdown as the new Covid-19 traffic light system starts across the country.', 'url': 'https://www.rnz.co.nz/news/national/457097/live-updates-traffic-light-system-operational-aucklanders-emerge-from-lockdown',
                         'urlToImage': 'https://www.rnz.co.nz/assets/news_crops/134970/eight_col_MicrosoftTeams-image_%282%29.png?1638476374', 'publishedAt': '2021-12-02T17:57:58Z', 'content': 'After nearly four months, Aucklanders have emerged from lockdown as the country enters the new traffic light system.\r\nAuckland cafes and gyms opened their doors today as New Zealand dropped alert lev… [+1360 chars]'},
                        {'source': {'id': None, 'name': 'eNCA'}, 'author': None, 'title': 'COVID-19 in SA: 11535 new cases, 44 deaths recorded - eNCA', 'description': 'The positivity rate currently stands at\xa022.4 percent and 51, 402 tests have been conducted in the past 24 hours.', 'url': 'https: // www.enca.com/news/covid-19-sa-11535-new-cases-44-deaths-recorded',
                         'urlToImage': 'https: // www.enca.com/sites/default/files/styles/facebook/public/2021-12/web_photo_covidtest_021221.jpg?h = 199d8c1f & itok = Yb90XNMt', 'publishedAt': '2021-12-02T17: 09: 00Z', 'content': 'JOHANNESBURG -\xa0The National Institute for Communicable Diseases (NICD) reported that 11, 535 new COVID-19 infections were recorded in the past 24 hours.\r\nGauteng accounts for over 8, 000 of the new cas… [+297 chars]'},
                        {'source': {'id': None, 'name': 'Independent.ie'}, 'author': "Eilish O'Regan", 'title': 'Booster shot bonus as Covid infections drop among people aged over 65 – 4163 confirmed cases today - Independent.ie', 'description': 'OLDER age groups are already reaping the benefits of Covid booster shots, with a drop in infections in people over 65.', 'url': 'https://www.independent.ie/irish-news/health/booster-shot-bonus-as-covid-infections-drop-among-people-aged-over-65-4163-confirmed-cases-today-41112280.html',
                         'urlToImage': 'https://www.independent.ie/irish-news/health/8cf45/41112279.ece/AUTOCROP/w1240h700/PL_4546539_highres.jpg', 'publishedAt': '2021-12-02T17:04:00Z', 'content': 'OLDER age groups are already reaping the benefits of Covid booster shots, with a drop in infections in people over 65.\r\nThe roll out of the booster campaign is seen as the\xa0health service up\xa0its defen… [+3944 chars]'},
                        {'source': {'id': None, 'name': 'The Punch'}, 'author': 'Agency Report', 'title': 'COVID-19: US announces second case of Omicron variant - The Punch', 'description': 'COVID-19: US announces second case of Omicron variant', 'url': 'https://punchng.com/covid-19-us-announces-second-case-of-omicron-variant/',
                         'urlToImage': 'https://cdn.punchng.com/wp-content/uploads/2021/10/28192155/HIV-Covid-19-pandemic.jpg', 'publishedAt': '2021-12-02T17:02:57Z', 'content': 'Health authorities in the midwestern US state of Minnesota announced Thursday they had found another case of the Omicron variant on American soil, this time in a man with no known recent internationa… [+1836 chars]'},
                        {'source': {'id': None, 'name': 'TCTMD'}, 'author': 'Todd Neale', 'title': 'Cardiopulmonary Tests Urged for Lasting Fatigue, Dyspnea After COVID-19 - TCTMD', 'description': 'Up to one in five patients who recover from COVID-19 have lingering symptoms months later, with dyspnea seen in half.', 'url': 'https://www.tctmd.com/news/cardiopulmonary-tests-urged-lasting-fatigue-dyspnea-after-covid-19',
                         'urlToImage': 'https://s3.amazonaws.com/prod.tctmd.com/public/2021-12/Cardiopulmonary%20Tests%20Urged%20for%20Lasting%20Fatigue%2C%20Dyspnea%20After%20COVID-19.jpg', 'publishedAt': '2021-12-02T17:00:00Z', 'content': 'Patients who have unexplained dyspnea months after recovering from COVID-19 often have objective signs of breathing problems on cardiopulmonary exercise testing (CPET) and meet criteria for myalgic e… [+5285 chars]'},
                        {'source': {'id': None, 'name': 'The Indian Express'}, 'author': 'AP', 'title': 'Germany excludes unvaccinated from parts of public life as Covid-19 cases spike - The Indian Express', 'description': "🔴 People who aren't vaccinated will be excluded from nonessential stores, cultural and recreational venues, and parliament will consider a general vaccine mandate, as part of an effort to curb coronavirus infections.",
                         'url': 'https://indianexpress.com/article/world/germany-excludes-unvaccinated-from-public-life-covid-19-cases-spike-7653071/', 'urlToImage': 'https://images.indianexpress.com/2021/12/GERMANY-1.jpg', 'publishedAt': '2021-12-02T16:57:47Z', 'content': 'German Chancellor Angela Merkel said Thursday that people who aren’t vaccinated will be excluded from nonessential stores, cultural and recreational venues, and parliament will consider a general vac… [+2107 chars]'},
                        {'source': {'id': None, 'name': 'National Post'}, 'author': 'Devika Desai', 'title': "What does Omicron mean for Canada's vaccinated majority? - National Post", 'description': 'And what does the new COVID-19 variant mean for the unvaccinated, single vaccinated and those with a booster shot?', 'url': 'https://nationalpost.com/news/what-does-omicron-mean-for-canadas-vaccinated-majority', 'urlToImage': 'https://smartcdn.prod.postmedia.digital/nationalpost/wp-content/uploads/2021/12/variant.jpeg', 'publishedAt': '2021-12-02T16:36:03Z', 'content': 'And what does the new COVID-19 variant mean for the unvaccinated, single vaccinated and those with a booster shot? \r\nDevika Desai\r\nSARS-CoV-2, also known as the novel coronavirus that causes Covid-19… [+10094 chars]'}]
    filtered_articles = process_news_api(articles_current, headlines)
    assert len(filtered_articles) == 14
